# Generated by Django 3.2.4 on 2021-06-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='welcomenote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcomenote', models.CharField(max_length=1000)),
            ],
        ),
    ]
