# Generated by Django 3.2.4 on 2021-06-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(help_text='Enter Event Name', max_length=20)),
                ('event_description', models.TextField(help_text='Enter Description', max_length=200)),
                ('event_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyModelName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_field_name', models.CharField(help_text='Enter field ', max_length=20)),
            ],
            options={
                'ordering': ['-my_field_name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=20)),
                ('designation', models.CharField(help_text='Designation', max_length=20)),
                ('branch', models.CharField(help_text='Branch', max_length=20)),
                ('roll_no', models.CharField(help_text='roll_no', max_length=20)),
                ('mobile_no', models.IntegerField(help_text='number', max_length=10)),
            ],
        ),
    ]
