# Generated by Django 3.2.4 on 2021-06-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_rename_events_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='mobile_no',
            field=models.CharField(help_text='number', max_length=10),
        ),
    ]
