# Generated by Django 3.1.4 on 2021-06-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='media/team')),
                ('position', models.CharField(default=None, max_length=100)),
                ('phone_number', models.IntegerField(blank=True)),
                ('fb_link', models.URLField(max_length=300)),
                ('insta_link', models.URLField(max_length=300)),
                ('linkedin_link', models.URLField(max_length=300)),
            ],
        ),
    ]
