# Generated by Django 3.2.4 on 2021-06-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_alter_team_mobile_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_note', models.TextField(help_text='Welcome Note', max_length=1000)),
            ],
        ),
    ]
