# Generated by Django 3.1 on 2021-06-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumiere', '0002_auto_20210621_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
