# Generated by Django 3.1.4 on 2021-07-06 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(default='placeholder.png', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=100)),
                ('image', models.ImageField(default='placeholder.png', upload_to='images')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GallaryEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='placeholder.png', upload_to='images')),
                ('video_link', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('note', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(default='placeholder.png', upload_to='images')),
                ('desription', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='media/team')),
                ('position', models.CharField(default=None, max_length=100)),
                ('phone_number', models.IntegerField(blank=True)),
                ('fb_link', models.URLField(max_length=300)),
                ('insta_link', models.URLField(max_length=300)),
                ('linkedin_link', models.URLField(max_length=300)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultboard.club')),
            ],
        ),
        migrations.CreateModel(
            name='MajorEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(default='placeholder.png', upload_to='images')),
                ('desription', models.CharField(blank=True, max_length=1000, null=True)),
                ('fb_page', models.CharField(blank=True, max_length=100, null=True)),
                ('inta_page', models.CharField(blank=True, max_length=100, null=True)),
                ('gallary_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cultboard.gallaryevent')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='gallary_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cultboard.gallaryevent'),
        ),
        migrations.AddField(
            model_name='club',
            name='note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cultboard.note'),
        ),
    ]
