# Generated by Django 3.2.1 on 2021-06-24 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cultboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Detail',
        ),
    ]
