# Generated by Django 3.2.4 on 2021-07-07 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cultboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='majorevent',
            old_name='desription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='upcomingevent',
            old_name='desription',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='majorevent',
            name='fb_page',
        ),
        migrations.RemoveField(
            model_name='majorevent',
            name='inta_page',
        ),
        migrations.AddField(
            model_name='majorevent',
            name='fb_link',
            field=models.URLField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='majorevent',
            name='insta_link',
            field=models.URLField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='majorevent',
            name='linkedin_link',
            field=models.URLField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
