# Generated by Django 3.2.1 on 2021-06-24 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cultboard', '0002_rename_details_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='GallaryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='placeholder.png', upload_to='images')),
                ('video_link', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='placeholder.png', upload_to='images')),
                ('position', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(default='placeholder.png', upload_to='images')),
                ('desription', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='detail',
            name='image',
            field=models.ImageField(default='placeholder,png', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.RenameModel(
            old_name='WecomeNote',
            new_name='Note',
        ),
        migrations.CreateModel(
            name='MajorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(default='placeholder.png', upload_to='images')),
                ('desription', models.CharField(blank=True, max_length=1000, null=True)),
                ('fb_page', models.CharField(blank=True, max_length=100, null=True)),
                ('inta_page', models.CharField(blank=True, max_length=100, null=True)),
                ('gallary_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cultboard.gallaryevent')),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(default='placeholder.png', upload_to='images')),
                ('gallary_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cultboard.gallaryevent')),
                ('note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cultboard.note')),
            ],
        ),
    ]
